repos:
  # Generic file hygiene checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # Python formatting (Black) - apply to all Python files
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3

  # Python import sorting (isort) - apply to all Python files
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "100"]

  # Python linting (flake8) - strict settings for code quality
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        # Strict but reasonable settings
        args: [
          "--max-line-length=100",
          "--extend-ignore=E203,W503"
        ]
        # Exclude third-party code but check our core code
        exclude: '^(src/pymc_core/hardware/lora/|examples/)'

  # Run pytest to ensure all tests pass
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        # Only run if Python files in src/ or tests/ have changed
        files: ^(src/|tests/|pyproject\.toml|setup\.py).*$
        args: ["-v", "--tb=short"]
      - id: pytest-fast
        name: pytest-fast (quick smoke test)
        entry: pytest
        language: system
        pass_filenames: false
        # Run a quick subset of tests for faster feedback
        files: ^(src/|tests/).*\.py$
        args: ["-v", "--tb=short", "-x", "--maxfail=3", "tests/test_basic.py", "tests/test_crypto.py"]
        stages: [manual]
