from openhop_core import CryptoUtils


# CryptoUtils tests
def test_crypto_utils_sha256():
    """Test SHA256 hashing."""
    data = b"Hello, World!"
    hash_result = CryptoUtils.sha256(data)
    assert len(hash_result) == 32

    # Same data should produce same hash
    hash_result2 = CryptoUtils.sha256(data)
    assert hash_result == hash_result2

    # Different data should produce different hash
    hash_result3 = CryptoUtils.sha256(b"Different data")
    assert hash_result != hash_result3


def test_crypto_utils_encrypt_then_mac():
    """Test encrypt-then-MAC functionality."""
    aes_key = b"0123456789abcdef"  # 16 bytes for AES
    shared_secret = b"0123456789abcdef0123456789abcdef"  # 32 bytes for HMAC
    plaintext = b"Hello, World!"

    # Encrypt-then-MAC
    encrypted = CryptoUtils.encrypt_then_mac(aes_key, shared_secret, plaintext)
    assert encrypted is not None
    assert len(encrypted) > len(plaintext)  # Should include MAC

    # MAC-then-decrypt (reverse operation)
    decrypted = CryptoUtils.mac_then_decrypt(aes_key, shared_secret, encrypted)
    # Remove padding (null bytes at the end)
    decrypted = decrypted.rstrip(b"\x00")
    assert decrypted == plaintext


def test_crypto_utils_key_exchange():
    """Test ECDH key exchange utilities."""
    from openhop_core import LocalIdentity

    # Create two identities for key exchange
    alice = LocalIdentity()
    bob = LocalIdentity()

    # Get the X25519 keys directly (they're already converted)
    alice_private_x25519 = alice.get_private_key()
    alice_public_x25519 = alice.get_shared_public_key()
    bob_private_x25519 = bob.get_private_key()
    bob_public_x25519 = bob.get_shared_public_key()

    # Perform ECDH
    alice_shared = CryptoUtils.scalarmult(alice_private_x25519, bob_public_x25519)
    bob_shared = CryptoUtils.scalarmult(bob_private_x25519, alice_public_x25519)

    # Both should compute the same shared secret
    assert alice_shared == bob_shared
    assert len(alice_shared) == 32


def test_ed25519_expand_seed_to_meshcore_64_same_public_key():
    """ed25519_expand_seed_to_meshcore_64 produces 64-byte key that derives to
    same public key as PyNaCl.

    MeshCore firmware (and meshcore-keygen) derives the public key by taking
    the first 32 bytes of the 64-byte private key and calling
    ed25519_derive_pub / crypto_scalarmult_ed25519_base_noclamp.
    So our expanded form must yield the same first-32-bytes scalar so the
    client gets the same pub key.
    """
    from nacl.bindings import crypto_scalarmult_ed25519_base_noclamp

    from openhop_core import LocalIdentity

    # Fixed seed for reproducible test
    seed = bytes.fromhex("70" + "65e18fd9fabb70c1ed90dca19907de" "698c88b709ea146eafd93d9b830c7b60")
    assert len(seed) == 32

    # Expand to 64-byte MeshCore format (SHA-512 + clamp)
    expanded = CryptoUtils.ed25519_expand_seed_to_meshcore_64(seed)
    assert len(expanded) == 64

    # Derive public key the way MeshCore firmware/keygen does: first 32 bytes =
    # scalar
    pub_from_expanded = crypto_scalarmult_ed25519_base_noclamp(expanded[:32])

    # PyNaCl LocalIdentity(seed=seed) derives pub via the same Ed25519 expansion internally
    identity = LocalIdentity(seed=seed)
    pub_from_pynacl = identity.get_public_key()

    assert pub_from_expanded == pub_from_pynacl, (
        "Expanded seed must yield same public key as PyNaCl so MeshCore " "clients derive correctly"
    )


# Sample keypair generated by meshcore-keygen (MeshCore firmware–compatible
# format). Used to verify our derivation matches:
#   pub = crypto_scalarmult_ed25519_base_noclamp(private_64[:32]).
MESHCORE_SAMPLE_PRIVATE_HEX = (
    "a8cdb06cef221ef0ee4e5e9d9d0829499cd304ca1bba47af2ea17d83b316726b"
    "e232b1da0388a2eb142d9a16ed66d4994a7ac40339ec1fbc3937f3b81f5dc62b"
)
MESHCORE_SAMPLE_PUBLIC_HEX = "8dfd59f1102e74845758096baf54d2b3a91413813e7c239baf75d1e9a0f04bf4"


def test_ed25519_expand_seed_matches_meshcore_keygen_format():
    """Deriving pub from first 32 bytes of a meshcore-keygen 64-byte private
    key matches expected pub.

    Uses a sample keypair generated by meshcore-keygen to verify our
    derivation (crypto_scalarmult_ed25519_base_noclamp(priv_64[:32]))
    matches the firmware/keygen format.
    """
    from nacl.bindings import crypto_scalarmult_ed25519_base_noclamp

    private_bytes = bytes.fromhex(MESHCORE_SAMPLE_PRIVATE_HEX)
    expected_public = bytes.fromhex(MESHCORE_SAMPLE_PUBLIC_HEX)
    assert len(private_bytes) == 64
    assert len(expected_public) == 32

    derived_public = crypto_scalarmult_ed25519_base_noclamp(private_bytes[:32])
    assert derived_public == expected_public, (
        "MeshCore format: pub must be derived from first 32 bytes of " "64-byte private key"
    )
