from types import SimpleNamespace

import pytest

from openhop_core.companion.contact_store import ContactStore
from openhop_core.companion.models import Contact
from openhop_core.node.dispatcher import Dispatcher
from openhop_core.node.handlers.ack import AckHandler
from openhop_core.node.handlers.path import PathHandler
from openhop_core.node.handlers.protocol_response import ProtocolResponseHandler
from openhop_core.protocol import CryptoUtils, Identity, LocalIdentity, Packet, PacketBuilder
from openhop_core.protocol.constants import (
    PAYLOAD_TYPE_ACK,
    PAYLOAD_TYPE_PATH,
    PAYLOAD_TYPE_RESPONSE,
    ROUTE_TYPE_FLOOD,
)
from openhop_core.protocol.packet_utils import PathUtils

LOCAL_IDENTITY = LocalIdentity(bytes(32))
SENDER_IDENTITY = LocalIdentity(bytes([0x16]) + bytes(31))

# Generated by the local MeshCore checkout's src/Utils.cpp::encryptThenMAC
# using its bundled C++ Crypto AES-128/HMAC implementation. The full PATH
# payload is dest_hash(0x3B), src_hash(0x2E), then its MAC+ciphertext for the
# plaintext 00 03 78 56 34 12 02 A5 (empty path, 6-byte firmware ACK).
MESHCORE_PATH_ACK_PAYLOAD = bytes.fromhex("3b2eb6ac4f0aace10b1ff6a0fa1b0cc050797ec1")


def _path_return(
    local_identity,
    peer_identity,
    path,
    extra_type,
    extra,
    path_len_encoded=None,
):
    shared_secret = Identity(peer_identity.get_public_key()).calc_shared_secret(
        local_identity.get_private_key()
    )
    return PacketBuilder.create_path_return(
        dest_hash=local_identity.get_public_key()[0],
        src_hash=peer_identity.get_public_key()[0],
        secret=shared_secret,
        path=path,
        extra_type=extra_type,
        extra=extra,
        path_len_encoded=path_len_encoded,
    )


def _handler_with_pending_ack(local_identity, contacts, ack_crc):
    dispatcher = SimpleNamespace(
        local_identity=local_identity,
        contact_book=contacts,
        _waiting_acks={ack_crc: object()},
    )
    return AckHandler(lambda _message: None, dispatcher)


def _packet_with_encrypted_inner(local_identity, peer_identity, inner):
    shared_secret = Identity(peer_identity.get_public_key()).calc_shared_secret(
        local_identity.get_private_key()
    )
    packet = Packet()
    packet.header = (PAYLOAD_TYPE_PATH << 2) | ROUTE_TYPE_FLOOD
    packet.path_len = 0
    packet.path = bytearray()
    packet.payload = bytearray(
        bytes([local_identity.get_public_key()[0], peer_identity.get_public_key()[0]])
        + CryptoUtils.encrypt_then_mac(shared_secret[:16], shared_secret, inner)
    )
    packet.payload_len = len(packet.payload)
    return packet


class _CallbackRadio:
    def set_rx_callback(self, callback):
        self.rx_callback = callback


@pytest.mark.asyncio
async def test_path_ack_tries_later_colliding_contact_after_mac_failure():
    """A valid PATH ACK must survive a one-byte source-hash collision."""
    local_identity = LOCAL_IDENTITY
    decoy = LocalIdentity(bytes([0x0C]) + bytes(31))
    sender = SENDER_IDENTITY
    assert decoy.get_public_key()[0] == sender.get_public_key()[0]

    contacts = ContactStore()
    contacts.add(Contact(public_key=decoy.get_public_key(), name="Decoy"))
    contacts.add(Contact(public_key=sender.get_public_key(), name="Sender"))
    ack_crc = 0x12345678
    packet = _path_return(
        local_identity,
        sender,
        path=[],
        extra_type=PAYLOAD_TYPE_ACK,
        extra=ack_crc.to_bytes(4, "little"),
    )
    assert len(packet.payload) == 20

    handler = _handler_with_pending_ack(local_identity, contacts, ack_crc)
    assert await handler.process_path_ack_variants(packet) == ack_crc


@pytest.mark.asyncio
async def test_path_ack_accepts_return_paths_larger_than_one_cipher_block():
    """ACK extraction must not be limited to the 20-byte outer PATH form."""
    local_identity = LOCAL_IDENTITY
    sender = SENDER_IDENTITY
    contacts = ContactStore()
    contacts.add(Contact(public_key=sender.get_public_key(), name="Sender"))
    ack_crc = 0x12345678
    packet = _path_return(
        local_identity,
        sender,
        path=list(range(11)),
        extra_type=PAYLOAD_TYPE_ACK,
        extra=ack_crc.to_bytes(4, "little"),
        path_len_encoded=PathUtils.encode_path_len(1, 11),
    )
    assert len(packet.payload) == 36

    handler = _handler_with_pending_ack(local_identity, contacts, ack_crc)
    assert await handler.process_path_ack_variants(packet) == ack_crc


@pytest.mark.asyncio
async def test_path_response_does_not_complete_ack_from_matching_path_bytes():
    """Only an ACK extra may resolve a pending ACK, never path bytes."""
    local_identity = LOCAL_IDENTITY
    sender = SENDER_IDENTITY
    contacts = ContactStore()
    contacts.add(Contact(public_key=sender.get_public_key(), name="Sender"))
    ack_crc = 0x12345678
    packet = _path_return(
        local_identity,
        sender,
        path=ack_crc.to_bytes(4, "little"),
        extra_type=PAYLOAD_TYPE_RESPONSE,
        extra=b"data",
        path_len_encoded=PathUtils.encode_path_len(1, 4),
    )
    assert len(packet.payload) == 20

    handler = _handler_with_pending_ack(local_identity, contacts, ack_crc)
    assert await handler.process_path_ack_variants(packet) is None


@pytest.mark.asyncio
async def test_meshcore_generated_six_byte_path_ack_is_accepted():
    """Decrypt a packet generated by MeshCore's own C++ AES/HMAC implementation."""
    contacts = ContactStore()
    contacts.add(Contact(public_key=SENDER_IDENTITY.get_public_key(), name="Sender"))
    ack_crc = 0x12345678
    packet = Packet()
    packet.header = (PAYLOAD_TYPE_PATH << 2) | ROUTE_TYPE_FLOOD
    packet.path_len = 0
    packet.path = bytearray()
    packet.payload = bytearray(MESHCORE_PATH_ACK_PAYLOAD)
    packet.payload_len = len(packet.payload)

    handler = _handler_with_pending_ack(LOCAL_IDENTITY, contacts, ack_crc)
    assert await handler.process_path_ack_variants(packet) == ack_crc


@pytest.mark.asyncio
@pytest.mark.parametrize("hash_size,hops", [(1, 63), (2, 32), (3, 21)])
async def test_path_ack_accepts_each_firmware_valid_path_boundary(hash_size, hops):
    """All valid MeshCore path hash widths and byte limits must parse."""
    encoded_path_len = PathUtils.encode_path_len(hash_size, hops)
    path = bytes(range(PathUtils.get_path_byte_len(encoded_path_len)))
    contacts = ContactStore()
    contacts.add(Contact(public_key=SENDER_IDENTITY.get_public_key(), name="Sender"))
    ack_crc = 0x12345678
    packet = _path_return(
        LOCAL_IDENTITY,
        SENDER_IDENTITY,
        path=path,
        extra_type=PAYLOAD_TYPE_ACK,
        extra=ack_crc.to_bytes(4, "little") + b"\x02\xa5",
        path_len_encoded=encoded_path_len,
    )

    handler = _handler_with_pending_ack(LOCAL_IDENTITY, contacts, ack_crc)
    assert await handler.process_path_ack_variants(packet) == ack_crc


@pytest.mark.asyncio
async def test_path_ack_accepts_reserved_extra_type_bits_like_meshcore():
    """MeshCore masks the extra-type high nibble before testing for ACK."""
    contacts = ContactStore()
    contacts.add(Contact(public_key=SENDER_IDENTITY.get_public_key(), name="Sender"))
    ack_crc = 0x12345678
    packet = _path_return(
        LOCAL_IDENTITY,
        SENDER_IDENTITY,
        path=[],
        extra_type=0xF0 | PAYLOAD_TYPE_ACK,
        extra=ack_crc.to_bytes(4, "little") + b"\x02\xa5",
    )

    handler = _handler_with_pending_ack(LOCAL_IDENTITY, contacts, ack_crc)
    assert await handler.process_path_ack_variants(packet) == ack_crc


@pytest.mark.asyncio
async def test_path_ack_rejects_wrong_destination_unknown_source_bad_mac_and_path_len():
    """Only an addressed, authenticated, well-formed PATH ACK may resolve a send."""
    contacts = ContactStore()
    contacts.add(Contact(public_key=SENDER_IDENTITY.get_public_key(), name="Sender"))
    ack_crc = 0x12345678

    wrong_destination = _path_return(
        LOCAL_IDENTITY,
        SENDER_IDENTITY,
        path=[],
        extra_type=PAYLOAD_TYPE_ACK,
        extra=ack_crc.to_bytes(4, "little"),
    )
    wrong_destination.payload[0] ^= 0xFF
    assert (
        await _handler_with_pending_ack(
            LOCAL_IDENTITY, contacts, ack_crc
        ).process_path_ack_variants(wrong_destination)
        is None
    )

    unknown_source = _path_return(
        LOCAL_IDENTITY,
        SENDER_IDENTITY,
        path=[],
        extra_type=PAYLOAD_TYPE_ACK,
        extra=ack_crc.to_bytes(4, "little"),
    )
    assert (
        await _handler_with_pending_ack(
            LOCAL_IDENTITY, ContactStore(), ack_crc
        ).process_path_ack_variants(unknown_source)
        is None
    )

    bad_mac = _path_return(
        LOCAL_IDENTITY,
        SENDER_IDENTITY,
        path=[],
        extra_type=PAYLOAD_TYPE_ACK,
        extra=ack_crc.to_bytes(4, "little"),
    )
    bad_mac.payload[-1] ^= 0x01
    assert (
        await _handler_with_pending_ack(
            LOCAL_IDENTITY, contacts, ack_crc
        ).process_path_ack_variants(bad_mac)
        is None
    )

    invalid_path_len = _packet_with_encrypted_inner(
        LOCAL_IDENTITY,
        SENDER_IDENTITY,
        b"\xc0" + bytes([PAYLOAD_TYPE_ACK]) + ack_crc.to_bytes(4, "little"),
    )
    assert (
        await _handler_with_pending_ack(
            LOCAL_IDENTITY, contacts, ack_crc
        ).process_path_ack_variants(invalid_path_len)
        is None
    )

    truncated_path = _packet_with_encrypted_inner(
        LOCAL_IDENTITY,
        SENDER_IDENTITY,
        bytes([PathUtils.encode_path_len(1, 63)]) + bytes(15),
    )
    assert (
        await _handler_with_pending_ack(
            LOCAL_IDENTITY, contacts, ack_crc
        ).process_path_ack_variants(truncated_path)
        is None
    )


@pytest.mark.asyncio
async def test_path_handler_updates_matched_contact_sends_reciprocal_and_resolves_waiter():
    """The full Core PATH flow mirrors MeshCore's path update and ACK completion."""
    decoy = LocalIdentity(bytes([0x0C]) + bytes(31))
    contacts = ContactStore()
    contacts.add(Contact(public_key=decoy.get_public_key(), name="Decoy"))
    contacts.add(Contact(public_key=SENDER_IDENTITY.get_public_key(), name="Sender"))
    ack_crc = 0x12345678
    out_path = bytes([0xA1, 0xB2])
    encoded_out_path_len = PathUtils.encode_path_len(1, 2)
    packet = _path_return(
        LOCAL_IDENTITY,
        SENDER_IDENTITY,
        path=out_path,
        extra_type=PAYLOAD_TYPE_ACK,
        extra=ack_crc.to_bytes(4, "little") + b"\x02\xa5",
        path_len_encoded=encoded_out_path_len,
    )
    packet.set_path(b"\xc3", PathUtils.encode_path_len(1, 1))

    dispatcher = Dispatcher(_CallbackRadio())
    dispatcher.local_identity = LOCAL_IDENTITY
    dispatcher.set_contact_book(contacts)
    waiting = dispatcher.expect_ack(ack_crc)

    ack_handler = AckHandler(lambda _message: None, dispatcher)
    ack_handler.set_ack_received_callback(dispatcher._register_ack_received)
    response_handler = ProtocolResponseHandler(lambda _message: None, LOCAL_IDENTITY, contacts)
    sent_reciprocals = []

    async def inject(packet_to_send):
        sent_reciprocals.append(packet_to_send)

    response_handler.set_packet_injector(inject)
    result = await PathHandler(
        lambda _message: None,
        ack_handler=ack_handler,
        protocol_response_handler=response_handler,
    )(packet)
    await response_handler.wait_for_pending_reciprocals()

    assert result.authenticated is True
    assert waiting.is_set()
    assert ack_crc not in dispatcher._waiting_acks
    assert contacts.get_by_key(SENDER_IDENTITY.get_public_key()).out_path == out_path
    assert contacts.get_by_key(decoy.get_public_key()).out_path == b""
    assert len(sent_reciprocals) == 1
    reciprocal = sent_reciprocals[0]
    assert reciprocal.is_route_direct()
    assert reciprocal.path_len == encoded_out_path_len
    assert bytes(reciprocal.path) == out_path
    assert reciprocal.payload[:2] == bytes(
        [SENDER_IDENTITY.get_public_key()[0], LOCAL_IDENTITY.get_public_key()[0]]
    )
    shared_secret = Identity(SENDER_IDENTITY.get_public_key()).calc_shared_secret(
        LOCAL_IDENTITY.get_private_key()
    )
    reciprocal_inner = CryptoUtils.mac_then_decrypt(
        shared_secret[:16], shared_secret, bytes(reciprocal.payload[2:])
    )
    assert reciprocal_inner[:3] == bytes([PathUtils.encode_path_len(1, 1), 0xC3, 0xFF])


@pytest.mark.asyncio
async def test_path_embedded_ack_notifies_listener_without_dispatcher_waiters():
    """Companion flow: the app (not the dispatcher) tracks expected ACK CRCs.

    Firmware Mesh::onRecvPacket decrypts every PATH addressed to this node and
    hands its extra (the embedded ACK for a flood text message) to processAck —
    with no dispatcher-level waiting-ack precondition. The PATH-embedded ACK
    must therefore reach the ack-received listener even when _waiting_acks is
    empty, or a companion client never sees delivery confirmation for a flood DM.
    """
    contacts = ContactStore()
    contacts.load_from([Contact(public_key=SENDER_IDENTITY.get_public_key(), name="peer")])
    ack_crc = 0x12345678
    dispatcher = SimpleNamespace(
        local_identity=LOCAL_IDENTITY,
        contact_book=contacts,
        _waiting_acks={},  # companion: nothing waits at dispatcher level
    )
    handler = AckHandler(lambda _message: None, dispatcher)

    notified = []

    async def listener(crc):
        notified.append(crc)

    handler.set_ack_received_callback(listener)

    packet = _path_return(
        LOCAL_IDENTITY,
        SENDER_IDENTITY,
        path=[],
        extra_type=PAYLOAD_TYPE_ACK,
        extra=ack_crc.to_bytes(4, "little"),
    )
    found = await handler.process_path_ack_variants(packet)
    assert found == ack_crc
    await handler._notify_ack_received(found)
    assert notified == [ack_crc]


class _CompanionMockRadio:
    """Minimal radio for a real CompanionRadio: set_rx_callback + async send."""

    def __init__(self):
        self.rx_callback = None
        self.sent: list[bytes] = []

    def set_rx_callback(self, callback):
        self.rx_callback = callback

    async def send(self, data: bytes) -> bool:
        self.sent.append(data)
        return True


@pytest.mark.asyncio
async def test_companion_tracked_ack_end_to_end_confirms_and_suppresses():
    """The real CompanionRadio wiring, end to end: an ACK whose CRC sits in the
    companion's app-side pending table must clear that entry, fire
    send_confirmed, and be marked do-not-retransmit — through the dispatcher's
    registered ACK handler, exactly as a received radio packet would travel.
    This is the central behavioural change (firmware onAckRecv processAck
    match): the listener's consumed result must survive the full
    CompanionRadio._on_ack_received -> dispatcher -> AckHandler chain.
    """
    from openhop_core.companion import CompanionRadio

    ack_crc = 0x0BADF00D
    comp = CompanionRadio(_CompanionMockRadio(), LocalIdentity())
    comp._track_pending_ack(ack_crc)

    confirmed: list[int] = []
    comp.on_send_confirmed(lambda crc, trip_ms: confirmed.append(crc))

    packet = Packet()
    packet.header = 1 << 2  # PAYLOAD_TYPE_ACK, route flood
    packet.path_len = 0
    packet.path = bytearray()
    packet.payload = bytearray(ack_crc.to_bytes(4, "little"))
    packet.payload_len = 4

    handler = comp.node.dispatcher._get_handler(PAYLOAD_TYPE_ACK)
    await handler(packet)

    assert ack_crc not in comp._pending_ack_crcs, "pending entry must be cleared"
    assert confirmed == [ack_crc], "send_confirmed must fire for the tracked CRC"
    assert (
        packet.is_marked_do_not_retransmit() is True
    ), "companion-consumed ACK must be suppressed from client-repeat forwarding"


@pytest.mark.asyncio
async def test_dispatcher_waiter_stays_marked_when_listener_raises():
    """Regression (review): marking a dispatcher-awaited ACK must not depend on
    the listener call succeeding. The pre-change code marked BEFORE notifying;
    that guarantee holds — a raising listener still leaves the packet marked
    (the exception propagates to the caller as before).
    """
    ack_crc = 0x12345678
    dispatcher = SimpleNamespace(
        local_identity=LOCAL_IDENTITY,
        contact_book=ContactStore(),
        _waiting_acks={ack_crc: object()},  # a dispatcher-level waiter exists
    )
    handler = AckHandler(lambda _m: None, dispatcher)

    async def raising_listener(crc):
        raise RuntimeError("listener blew up")

    handler.set_ack_received_callback(raising_listener)
    packet = Packet()
    packet.header = 1 << 2  # PAYLOAD_TYPE_ACK, route flood
    packet.path_len = 0
    packet.path = bytearray()
    packet.payload = bytearray(ack_crc.to_bytes(4, "little"))
    packet.payload_len = 4
    with pytest.raises(RuntimeError):
        await handler(packet)
    assert (
        packet.is_marked_do_not_retransmit() is True
    ), "a dispatcher-awaited ACK must stay marked even when the listener fails"


@pytest.mark.asyncio
@pytest.mark.parametrize("listener_consumes", [True, False])
async def test_decrypted_path_ack_is_authenticated_regardless_of_consumption(listener_consumes):
    """Firmware parity for PATH packets (Mesh::onRecvPacket): a successful
    MAC-then-decrypt alone proves the PATH belongs to this identity, so the
    handler returns authenticated — whether or not the embedded CRC matched a
    pending send (that match is processAck's separate, app-level decision).
    HandlerResult.authenticated then drives do-not-retransmit in the dispatcher
    and the forwarding decision in the companion bridge.
    """
    contacts = ContactStore()
    contacts.add(Contact(public_key=SENDER_IDENTITY.get_public_key(), name="peer"))
    ack_crc = 0x12345678
    dispatcher = Dispatcher(_CallbackRadio())
    dispatcher.local_identity = LOCAL_IDENTITY
    dispatcher.set_contact_book(contacts)
    notified: list[int] = []

    def listener(crc):
        notified.append(crc)
        return listener_consumes

    dispatcher.set_ack_received_listener(listener)

    ack_handler = AckHandler(lambda _m: None, dispatcher)
    ack_handler.set_ack_received_callback(dispatcher._register_ack_received)

    packet = _path_return(
        LOCAL_IDENTITY,
        SENDER_IDENTITY,
        path=[],
        extra_type=PAYLOAD_TYPE_ACK,
        extra=ack_crc.to_bytes(4, "little"),
    )
    result = await PathHandler(lambda _m: None, ack_handler=ack_handler)(packet)
    assert result.authenticated is True, (
        "a MAC-verified PATH is authenticated independent of CRC consumption"
    )
    assert notified == [ack_crc], "the embedded CRC must still reach the listener"


@pytest.mark.asyncio
@pytest.mark.parametrize("is_async", [False, True])
@pytest.mark.parametrize(
    "result, expect_marked",
    [(True, True), (False, False), (None, False)],
)
async def test_ack_received_listener_consumed_contract(is_async, result, expect_marked):
    """Contract for AckReceivedCallback: a truthy return means the ACK matched one of this node's
    pending sends (mark do-not-retransmit); False/None means not mine (leave it). Both sync and
    async listeners honour it, and a None-returning listener stays backward-compatible."""
    ack_crc = 0x0BADF00D
    dispatcher = Dispatcher(_CallbackRadio())
    dispatcher.local_identity = LOCAL_IDENTITY
    dispatcher.set_contact_book(ContactStore())

    if is_async:

        async def listener(crc):
            return result

    else:

        def listener(crc):
            return result

    dispatcher.set_ack_received_listener(listener)

    handler = AckHandler(lambda _m: None, dispatcher)
    handler.set_ack_received_callback(dispatcher._register_ack_received)

    packet = Packet()
    packet.header = 1 << 2  # PAYLOAD_TYPE_ACK, route flood
    packet.path_len = 0
    packet.path = bytearray()
    packet.payload = bytearray(ack_crc.to_bytes(4, "little"))
    packet.payload_len = 4
    await handler(packet)
    assert packet.is_marked_do_not_retransmit() is expect_marked
